// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeAgendamentoDeViagens.Data;

namespace SistemaDeAgendamentoDeViagens.Migrations
{
    [DbContext(typeof(ViagemContext))]
    partial class ViagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Assento", b =>
                {
                    b.Property<int>("Numero_ass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Classe_ass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Numero_ass");

                    b.ToTable("Assentos");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.AssentoVoo", b =>
                {
                    b.Property<long?>("Numero_ass")
                        .HasColumnType("bigint");

                    b.Property<long?>("VooId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AssentosNumero_ass")
                        .HasColumnType("int");

                    b.HasKey("Numero_ass", "VooId");

                    b.HasIndex("AssentosNumero_ass");

                    b.HasIndex("VooId");

                    b.ToTable("AssentoVoos");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Passageiro", b =>
                {
                    b.Property<long?>("PassageiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Bairro_pas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CEP_pas")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CPF_pas")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Cidade_pas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Data_nasc_pas")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_pas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome_pas")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("Passaporte_pas")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Sexo_pas")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UF_pas")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("PassageiroId");

                    b.HasIndex("CPF_pas")
                        .IsUnique();

                    b.HasIndex("Email_pas")
                        .IsUnique();

                    b.HasIndex("Passaporte_pas")
                        .IsUnique();

                    b.ToTable("Passageiros");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Reserva", b =>
                {
                    b.Property<long?>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Data_res")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<long?>("PassageiroId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Preco_res")
                        .HasColumnType("decimal(6,2)");

                    b.Property<long?>("VooId")
                        .HasColumnType("bigint");

                    b.HasKey("ReservaId");

                    b.HasIndex("PassageiroId");

                    b.HasIndex("VooId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Voo", b =>
                {
                    b.Property<long?>("VooId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Data_chegada_voo")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data_partida_voo")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao_voo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Destino_voo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Origem_voo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VooId");

                    b.ToTable("Voos");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.AssentoVoo", b =>
                {
                    b.HasOne("SistemaDeAgendamentoDeViagens.Models.Assento", "Assentos")
                        .WithMany("AssentoVoos")
                        .HasForeignKey("AssentosNumero_ass");

                    b.HasOne("SistemaDeAgendamentoDeViagens.Models.Voo", "Voos")
                        .WithMany("AssentoVoos")
                        .HasForeignKey("VooId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assentos");

                    b.Navigation("Voos");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Reserva", b =>
                {
                    b.HasOne("SistemaDeAgendamentoDeViagens.Models.Passageiro", "Passageiro")
                        .WithMany("Reservas")
                        .HasForeignKey("PassageiroId");

                    b.HasOne("SistemaDeAgendamentoDeViagens.Models.Voo", "Voo")
                        .WithMany("Reservas")
                        .HasForeignKey("VooId");

                    b.Navigation("Passageiro");

                    b.Navigation("Voo");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Assento", b =>
                {
                    b.Navigation("AssentoVoos");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Passageiro", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SistemaDeAgendamentoDeViagens.Models.Voo", b =>
                {
                    b.Navigation("AssentoVoos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
